# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE = "achiu-auS"
MACHINE_IP = "192.168.56.110"
PROVIDER = "virtualbox"
FLANNEL_INTERFACE="--flannel-iface=eth1"
CPUS = 4
MEMORY = 4096

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider PROVIDER do |vb|
    vb.cpus = CPUS
    vb.memory = MEMORY
  end
  config.vm.define MACHINE do |current|
    current.vm.provider PROVIDER do |vb|
      vb.name = MACHINE
    end
    current.vm.hostname = MACHINE
    current.vm.network "private_network", ip: MACHINE_IP
    config.vm.provision "shell", path: "scripts/setup.sh"
    current.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode=644 --tls-san $(hostname) --bind-address=#{MACHINE_IP} --advertise-address=#{MACHINE_IP} --node-ip=#{MACHINE_IP} #{FLANNEL_INTERFACE}" sh -
      cd /vagrant/confs
      kubectl apply -f app-one.yml
      kubectl apply -f app-two.yml
      kubectl apply -f app-three.yml
      kubectl apply -f ingress.yml
      echo "#{MACHINE_IP} app1.com app2.com app3.com" >> /etc/hosts
    SHELL
  end
end
