# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE_1 = "achiu-auS"
MACHINE_1_IP = "192.168.56.110"
MACHINE_2 = "achiu-auSW"
MACHINE_2_IP = "192.168.56.111"
PROVIDER = "virtualbox"
FLANNEL_INTERFACE="--flannel-iface=eth1"
CPUS = 1
MEMORY = 1024
TARGET="/vagrant/node-token"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider PROVIDER do |vb|
    vb.cpus = CPUS
    vb.memory = MEMORY
  end
  config.vm.define MACHINE_1 do |current|
    current.vm.provider PROVIDER do |vb|
      vb.name = MACHINE_1
    end
    current.vm.hostname = MACHINE_1
    current.vm.network "private_network", ip: MACHINE_1_IP
    config.vm.provision "shell", path: "scripts/setup.sh"
    current.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode=644 --bind-address=#{MACHINE_1_IP} --advertise-address=#{MACHINE_1_IP} --node-ip=#{MACHINE_1_IP} #{FLANNEL_INTERFACE}" sh -
      cp /var/lib/rancher/k3s/server/node-token #{TARGET}
    SHELL
  end
  config.vm.define MACHINE_2 do |current|
    current.vm.provider PROVIDER do |vb|
      vb.name = MACHINE_2
    end
    current.vm.hostname = MACHINE_2
    current.vm.network "private_network", ip: MACHINE_2_IP
    config.vm.provision "shell", path: "scripts/setup.sh"
    current.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --node-ip=#{MACHINE_2_IP} #{FLANNEL_INTERFACE}"\
        K3S_URL=https://#{MACHINE_1_IP}:6443 K3S_TOKEN=$(cat #{TARGET}) sh -
      rm -rf #{TARGET}
    SHELL
  end
end

